In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 



In [29]:
%matplotlib

Using matplotlib backend: Qt5Agg


# Import Iris dataset

In [30]:
from sklearn.datasets import load_iris

In [31]:
iris_dataset = load_iris()

# Know your data

In [32]:
print("keys of iris_dataset:\n {}".format(iris_dataset.keys()))

keys of iris_dataset:
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [33]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [34]:
print("Features names: \n {}".format(iris_dataset['feature_names']))

Features names: 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [35]:
print("shape of data {}".format(iris_dataset['data'].shape))

shape of data (150, 4)


In [36]:
print("first five columns of data : \n {}".format(iris_dataset['data'][:5]))

first five columns of data : 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [37]:
print("Shape of target : {}".format(iris_dataset['target'].shape))

Shape of target : (150,)


In [38]:
print("target : \n {}".format(iris_dataset['target']))

target : 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# Split data between train and test

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

In [40]:
print("X_train shape : {}".format(X_train.shape))
print("y_train shape : {}".format(y_train.shape))

X_train shape : (112, 4)
y_train shape : (112,)


In [41]:
print("X_test shape : {}".format(X_test.shape))
print("y_test shape : {}".format(y_test.shape))

X_test shape : (38, 4)
y_test shape : (38,)


# create dataframe from data in X_train

In [42]:
iris_dataframe = pd.DataFrame(X_train,columns=iris_dataset['feature_names'])

In [43]:
iris_dataframe.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.9               3.0                4.2               1.5
1                5.8               2.6                4.0               1.2
2                6.8               3.0                5.5               2.1
3                4.7               3.2                1.3               0.2
4                6.9               3.1                5.1               2.3

In [44]:
grr = pd.scatter_matrix(iris_dataframe,c=y_train,figsize=(15,15),marker='o',hist_kwds={'bins':20},s=60,alpha=.8,cmap=mglearn.cm3)

AttributeError: module 'pandas' has no attribute 'scatter_matrix'

# Import KNeighborsClassifier

In [45]:
from sklearn.neighbors import KNeighborsClassifier

#from module neighbors we are importing class KNeighborsClassifier

In [46]:
knn = KNeighborsClassifier(n_neighbors=1)

#we need to instantiate the class into an object

# To build the model on the training set call the fit method of the knn

In [47]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

# making prediction


In [57]:
X_new = np.array([[5,2.9,4,0.4]])

#new sample to be classified 

print("Shape of new sample : {}".format(X_new.shape))

Shape of new sample : (1, 4)


In [58]:
prediction = knn.predict(X_new)

print("prediction : {}".format(prediction))

print("predicted target name : {}".format(iris_dataset['target_names'][prediction]))

prediction : [1]
predicted target name : ['versicolor']


In [59]:
print(knn.predict_proba(X_new))

[[0. 1. 0.]]


# Evaluating the model

In [60]:
y_pred = knn.predict(X_test)

print("Test set predictions : \n {}".format(y_pred))

Test set predictions : 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [62]:
print("Test set score : {:.2f}".format(np.mean(y_pred==y_test)))

Test set score : 0.97


In [65]:
print("Test se score : {:.2f}".format(knn.score(X_test,y_test)))

Test se score : 0.97
